### ISSUE TITLE
Just `npm install` and `npm start`

### ISSUE THREAD

**Issue by xtoddx** [moneypenny/svg-scribbler#1]
I think that if you make bower a devDependency you can do something like

``` json
"scripts": {
  "start": "./.node_modules/gulp watch",
  "postinstall": "./.node_modules/bower install",
  "test": "jest"
} 
```

and follow the more standard install/start flow instead of having to specify the commands to run in the README.

**Comment by cheshire137** [comment]
Nice!

**Comment by cheshire137** [comment]
Fixed with https://github.com/moneypenny/svg-scribbler/commit/36673f7fbb6fe67dd7fcdd3de77d13cb957c1e0e
